version: '3'

services:
  tor-nginx:
    image: i5heu/tor-simple-hidden-website
    restart: always
    volumes:
      - ./tor-config:/etc/tor:Z
      - ./tor-data:/var/lib/tor:Z
      - ./logs:/var/log/tor:Z
      - ./nginx-config:/etc/nginx/sites-enabled:Z
      - ./web-public:/var/www/html:Z
